### PR TITLE
moved to sha512

### LINKED ISSUE #76: setup.ini no longer uses md5
In fact, they use sha512 sums now.
This breaks installing packages for me (passing `-X` doesn't seem to help)
Here is the latest setup.ini from mirrors.kernel.org for reference: http://sprunge.us/PNAg

### PR DESCRIPTION
**Pull request by 5paceToast**
Signed-off-by: 5paceToast <5paceToast@users.noreply.github.com>
Fixes #76 
Notes:
- not sure what BC is.
- backwards compatibility is broken, but setup.ini is standardized. adding compatibility layer should be simple, but I'm not interested in doing so
- did not write unit test, possible TODO

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes (sha512 support)
| BC breaks?      | ?
| Deprecations?   | ?
| Tests pass?     | yes
| Related tickets | #76 
| License         | GNU GPLv3

### CODE REVIEW

**Comment by alquerci** [comment]
Hi @5paceToast thank you to report this problem and to fix it.

BC means backwards compatibility.

It's useless to rename all references to `md5` by `sha512` (`readme`, `man`, `completion` have been forgotten). Replaced `hashlib.md5` by `hashlib.sha512` it's all we need to work.

For keep the meaning updated messages it's a good idea maybe like that:

    checksum of cached package doesn't match checksum in setup.ini from mirror

Unit test for that is only by replaced `hashlib.md5` by `hashlib.sha512` on the tests.

In a second step the `md5` command should be deprecated and replaced by another named `checksum` or a better one. The name of the command, variables and methods should not depend on the algorithm used. Because the initial goal of this command is to check if a cache file is corrupt.

**Comment by 5paceToast** [comment]
I believe in self documenting code, so replacing the name of a variable definitely helps.
I do agree that "checksum" instead of md5/sha512 is optimal, and simply have a setting that chooses which hashlib function to use elsewhere.
I haven't worked with man, don't use the completion (I run zsh) and didn't bother updating the readme, sorry for that. My goal was just to get my own install working again as fast as possible, and sed does magic.

**Comment by alquerci** [comment]
For a quick fix I think it's better to change the minimum code to avoid any inconvenience.

I will see tomorrow for fix it.

**Comment by alquerci** [comment]
Closing in favour of #79

**Pull request closed without merging**
